FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs
COPY scripts/ scripts
COPY test_data/ test_data
